from products.api.views.product_filters_view import ProductFiltersOrderingView
from products.api.views.product_viewset import ProductListViewSet
from products.api.views.product_rand_view import ProductRandView