version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        gunicorn marketplace_api.wsgi:application --bind 0.0.0.0:8000     
      "
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env-docker


volumes:
  postgres_data:
