services:
  web:
    build: .
    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        python manage.py migrate --noinput &&
        gunicorn marketplace_api.wsgi:application --bind 0.0.0.0:8000     
      "
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:

